<?php
//
// Load the dibs standard object
//
$standard = Mage::getModel('dibs/standard');
?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>											
           <?php echo $this->__('DIBS_LABEL_1'); ?>
            <?php
            	if ($standard->showTrustedList()) {
				        ?>
				        <br><br>
				        <?php
				        //
				        // Show trusted logos
				        //
				        $logoArray = explode(',', $standard->getConfigData('dibslogos'));
				        foreach($logoArray as $item) {
				        	switch ($item) {
				        		case 'DIBS': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/dibslogo.gif') ?>" border="0" title="DIBS | Secure Payment Services (www.dibspayment.com)" />&nbsp;&nbsp;<?php
				        			break;
				        		} 
				        		case 'VISA_SECURE': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/verifiedbyvisa.gif') ?>" border="0" />&nbsp;&nbsp;<?php
				        			break;
				        		} 
				        		case 'MC_SECURE': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/mastercardsecurecode.gif') ?>" border="0" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'JCB_SECURE': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/jcbsecure.gif') ?>" border="0" />&nbsp;&nbsp;<?php
				        			break;
				        		}  
				        		case 'PCI': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/pci.gif') ?>" border="0" />&nbsp;&nbsp;<?php
				        			break;
				        		} 	
				        	}
				        }
				      }
				      
				      if ($standard->showCardsList()) {
				        ?>
			        	<br><br>
				        <?php echo $this->__('DIBS_LABEL_2') ?>
				        <br>
				        <?php
				        //
				        // Show card logos
				        //
				        $logoArray = explode(',', $standard->getConfigData('dibslogos'));
				        foreach($logoArray as $item) {
				        	switch ($item) {
				        		case 'AMEX': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/amex.gif') ?>" border="0" title="American Express" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'BAX': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/bax.gif') ?>" border="0" title="BankAxess" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'DIN': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/diners.gif') ?>" border="0" title="Diners Club" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'DK': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/dankort.gif') ?>" border="0" title="Dankort" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'FFK': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/forbrugforeningen.gif') ?>" border="0" title="Forbrugsforeningen Card" />&nbsp;&nbsp;<?php
				        			break;
				        		}  
				        		case 'JCB': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/jcb.gif') ?>" border="0" title="JCB (Japan Credit Bureau)" />&nbsp;&nbsp;<?php
				        			break;
				        		} 
				        		case 'MC': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/mastercard.gif') ?>" border="0" title="MasterCard" />&nbsp;&nbsp;<?php
				        			break;
				        		}  
				        		case 'MTRO': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/maestro.gif') ?>" border="0" title="Maestro" />&nbsp;&nbsp;<?php
				        			break;
				        		}  
				        		case 'MOCA': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/mobilcash.gif') ?>" border="0" title="Mobilcash" />&nbsp;&nbsp;<?php
				        			break;
				        		} 
				        		case 'VISA': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/visa.gif') ?>" border="0" title="Visa" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'ELEC': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/visaelectron.gif') ?>" border="0" title="Visa Electron" />&nbsp;&nbsp;<?php
				        			break;
				        		} 
				        		case 'AKTIA': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/aktia.gif') ?>" border="0" title="Aktia Web Payment" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'DNB': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/danskenetbetaling.gif') ?>" border="0" title="Danske Netbetaling (Danske Bank)" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'EDK': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/edankort.gif') ?>" border="0" title="eDankort" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'ELV': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/bankeinzug.gif') ?>" border="0" title="Bank Einzug (eOLV)" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'EW': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/ewire.gif') ?>" border="0" title="eWire" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'FSB': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/swedbankdirektbetaling.gif') ?>" border="0" title="Swedbank Direktbetalning" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'GIT': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/getitcard.gif') ?>" border="0" title="Getitcard" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'ING': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/ideal.gif') ?>" border="0" title="ING iDeal Payment" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'SEB': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/seb.gif') ?>" border="0" title="SEB Direktbetalning" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'SHB': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/shbdirektbetaling.gif') ?>" border="0" title="SHB Direktbetalning" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'SOLO': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/nordea.gif') ?>" border="0" title="Nordea Solo-E betaling" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        		case 'VAL': {
				        			?><img src="<?php echo $this->getSkinUrl('images/dibs/valus.gif') ?>" border="0" title="Valus" />&nbsp;&nbsp;<?php
				        			break;
				        		}
				        	}
				        }
				      }
				      ?>
        </li>
    </ul>
</fieldset>
